version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server 
    ports:
     - "6379:6379"

  flask-sample:
    build: .
    depends_on:
      - db
      - redis
    ports:
     - "5000:5000"
    environment:
     - DBUSER=postgres
     - DBPASS=changeme
     - DBHOST=db
     - DBNAME=postgres
    volumes:
      - "/home/niraj/Desktop/test/Blog/:/projects/"
    

  db:
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
    ports:
     - "5432:5432"

  frontend:
    build:
      context: /home/niraj/Desktop/arjuncodes/login+regis/client/
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
