version: '3'
services:
  flask-sample:
    build: .
    # depends_on:
    #   - db
    ports:
     - "5000:5000"
    environment:
     - DBUSER=postgres
     - DBPASS=changeme
     - DBHOST=db
     - DBNAME=postgres

  # db:
  #   image: postgres:9.4
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: changeme
  #   volumes:
  #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
